server.port=8888
spring.application.name=config-server

spring.cloud.config.server.git.uri=https://github.com/Commandarprime/banking-config
spring.cloud.config.server.git.default-label=master

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.config.import=configserver:http://localhost:8888
