server.port=9005

spring.application.name=statement-service
spring.datasource.url=jdbc:postgresql://localhost:5432/statement_db
spring.datasource.username=postgres
spring.datasource.password=prime commandar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
